app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('main.urls', namespace='main'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:item_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:item_id>/', views.cart_remove, name='cart_remove'),
    path('update/<int:item_id>/', views.CartUpdateView.as_view(), name='cart_update'),
]

main/urls.py
from .views import CatalogView, ClothingItemDetailView
from django.urls import path

app_name = 'main'

urlpatterns = [
    path('', CatalogView.as_view(), name='catalog'),
    path('item/<slug:slug>/', ClothingItemDetailView.as_view(),
         name='clothing_item_detail')
]

orders/urls.py
from django.urls import path
from .views import order_create, order_success

app_name = 'orders'

urlpatterns = [
    path('create/', order_create, name='order_create'),
    path('completed/', order_success, name='order_success'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .cart import Cart
from django.views import View
from main.models import ClothingItem, ClothingItemSize, Size

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/cart_detail.html', {'cart': cart})

def cart_add(request, item_id):
    cart = Cart(request)
    clothing_item = get_object_or_404(ClothingItem, id=item_id)
    size = request.POST.get('size')

    if size:
        try:
            size_obj = Size.objects.get(name=size)
            clothing_item_size = ClothingItemSize.objects.get(clothing_item=clothing_item,
                                                              size=size_obj)
            if not clothing_item_size.available:
                return redirect('cart:cart_detail')
        except Size.DoesNotExist:
            return redirect('cart:cart_detail')
        except ClothingItemSize.DoesNotExist:
            return redirect('cart:cart_detail')
    else:
        available_sizes = clothing_item.sizes.filter(clothingitemsize__available=True)
        if available_sizes.exists():
            size_obj = available_sizes.first()
            size = size_obj.name
        else:
            return redirect('cart:cart_detil')

    cart.add(clothing_item, size)
    return redirect('cart:cart_detail')


def cart_remove(request, item_id):
    cart = Cart(request)
    clothing_item = get_object_or_404(ClothingItem, id=item_id)
    cart.remove(clothing_item)
    return redirect('cart:cart_detail')


class CartUpdateView(View):
    def post(self, request, item_id):
        cart = Cart(request)
        quantity = request.POST.get('quantity', 1)
        try:
            quantity = int(quantity)
            if quantity < 1:
                quantity = 1
        except ValueError:
            quantity = 1
        clothing_item = get_object_or_404(ClothingItem, id=item_id)

        if quantity > 0:
            cart.add(clothing_item, cart.cart[str(item_id)]['size'], quantity)
        else:
            cart.remove(clothing_item)

        return redirect('cart:cart_detail')

cart/templates/cart/cart_detail.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Reverence Interlude - Cart{% endblock title %}

{% block content %}
    <h1 class="text-center mb-5">Shopping Cart</h1>
    <div class="table-cart">
        <div class="table-head d-flex justify-content-between align-items-center">
            <div class="left-side-head">
                <p class="table-p">Product</p>
            </div>
            <div class="right-side-head d-flex gap-3">
                <p class="table-p c-item-total">Price</p>
                <p class="table-p c-item-quantity">Quantity</p>
                <p class="table-p c-item-price">Total</p>
            </div>
        </div>
        <div class="table-items">
            {% if cart|length == 0 %}
                <div class="empty-cart-message d-flex flex-column justify-content-center align-items-center text-center">
                    <h3 class="mt-5 mb-5">Your cart is empty.</h3>
                    <a href="{% url "main:catalog" %}" class="default-btn">Product list</a>
                </div>
            {% else %}
                {% for item in cart %}
                    <div class="cart-item d-flex justify-content-between align-items-center">
                        <div class="left-side-items d-flex">
                            <div class="c-item-img">
                                <img src="{{ item.item.image.url }}" alt="">
                            </div>
                            <div class="c-item-info">
                                <a href="{% url "main:clothing_item_detail" item.item.slug %}"
                                    class="item-name-in-cart p-3">{{ item.item.name }}
                                </a>
                                <p class="item-size-bottom fw-bold p-3">{{ item.size }}</p>
                            </div>
                        </div>
                        <div class="right-side-items d-flex gap-3">
                            <div class="c-item-price">
                                ${{ item.total_price|floatformat:2 }}
                            </div>
                            <div class="c-item-quantity">
                                <form action="{% url "cart:cart_update" item.item.id %}"
                                    id="update-form-{{ item.item.id }}" method="post" class="c-quantity-form">
                                    {% csrf_token %}
                                    <input type="number" class="text-center" name="quantity" value="{{ item.quantity }}"
                                        min="1" required id="quantity-{{ item.item.id }}" oninput="updateCart({{ item.item.id }})">
                                    <a href="{% url "cart:cart_remove" item.item.id %}">Remove</a>
                                </form>
                            </div>
                            <div class="c-item-total">
                                ${{ item.total_price|floatformat:2 }}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    {% if cart|length > 0 %}
        <h3 class="total_price_cart mt-5">Total price: ${{ cart.get_total_price|floatformat:2 }}</h3>
        <a href="{% url 'orders:order_create' %}" class="default-btn mt-3">Create order</a>
    {% endif %}

    <script>
        let timeout = null;

        function updateCart(itemId) {
            clearTimeout(timeout);

            timeout = setTimeout(function() {
                document.getElementById('update-form-' + itemId).submit();
            }, 1000);
        }
    </script>
{% endblock content %}