app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('main.urls', namespace='main'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:item_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:item_id>/', views.cart_remove, name='cart_remove'),
    path('update/<int:item_id>/', views.CartUpdateView.as_view(), name='cart_update'),
]

main/urls.py
from .views import CatalogView, ClothingItemDetailView
from django.urls import path

app_name = 'main'

urlpatterns = [
    path('', CatalogView.as_view(), name='catalog'),
    path('item/<slug:slug>/', ClothingItemDetailView.as_view(),
         name='clothing_item_detail')
]

main/models.py
from django.db import models


class Size(models.Model):
    name = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name'])]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_item_count(self):
        return ClothingItem.objects.filter(category=self).count()

class ClothingItem(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    available = models.BooleanField(default=True)
    sizes = models.ManyToManyField(Size, through='ClothingItemSize',
                                   related_name='clothing_item', blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE,
                                 related_name='clothing_items')
    image = models.ImageField(upload_to='product/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True)
    price = models.DecimalField(max_digits=20, decimal_places=2)
    discount = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return self.name

    def get_price_with_discount(self):
        if self.discount > 0:
            return round(self.price * (1 - (self.discount / 100)), 2)
        return round(self.price, 2)

class ClothingItemSize(models.Model):
    clothing_item = models.ForeignKey(ClothingItem, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    available = models.BooleanField(default=True)

    class Meta:
        unique_together = ('clothing_item', 'size')

class ItemImage(models.Model):
    product = models.ForeignKey(ClothingItem, related_name='images',
                                on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product/%Y/%m/%d', blank=True)

    def __str__(self):
        return f'{self.product.name} - {self.image.name}'

main/views.py
from django.views.generic import ListView, DetailView
from .models import ClothingItem, Category, Size, \
    ClothingItemSize
from django.db.models import Q


class CatalogView(ListView):
    model = ClothingItem
    template_name = 'main/product/list.html'
    context_object_name = 'clothing_items'


    def get_queryset(self):
        queryset = super().get_queryset()
        category_slugs = self.request.GET.getlist('category')
        size_names = self.request.GET.getlist('size')
        min_price = self.request.GET.get('min_price')
        max_price = self.request.GET.get('max_price')
        search_query = self.request.GET.get('q')

        if category_slugs:
            queryset = queryset.filter(category__slug__in=category_slugs)

        if size_names:
            queryset = queryset.filter(
                Q(sizes__name__in=size_names) & Q(sizes__clothingitemsize__available=True)
            ).distinct()

        if min_price:
            queryset = queryset.filter(price__gte=min_price)

        if max_price:
            queryset = queryset.filter(price__lte=max_price)

        if search_query:
            queryset = queryset.filter(
                Q(name__icontains=search_query) |
                Q(description__icontains=search_query)
            ).distinct()

        return queryset


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['sizes'] = Size.objects.all()
        context['selected_categories'] = self.request.GET.getlist('category')
        context['selected_sizes'] = self.request.GET.getlist('size')
        context['min_price'] = self.request.GET.get('min_price', '')
        context['max_price'] = self.request.GET.get('max_price', '')

        return context


class ClothingItemDetailView(DetailView):
    model = ClothingItem
    template_name = 'main/product/detail.html'
    context_object_name = 'clothing_item'
    slug_field = 'slug'
    slug_url_kwarg = 'slug'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        clothing_item = self.object
        available_sizes = ClothingItemSize.objects.filter(clothing_item=clothing_item,
                                                           available=True)
        context['available_sizes'] = available_sizes
        return context

main/templates/main/product/detail.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Reverence Interlude - {{ clothing_item.name }}{% endblock title %}

{% block content %}
    <div class="detail-product d-flex">
        <div class="detail-img d-flex justify-content-center">
            {% for image in clothing_item.images.all %}
                <img src="{{ image.image.url }}" style="display: none;"
                    alt="{{ clothing_item.name }}" class="detail-image" data-index="{{ forloop.counter0 }}">
            {% endfor %}
            <div class="image-nav d-flex justify-content-between">
                <buttton class="prev-btn">&lsaquo;</buttton>
                <buttton class="next-btn">&rsaquo;</buttton>
            </div>
        </div>

        <div class="detail-description">
            <h2 class="text-uppercase">{{ clothing_item.name }}</h2>
            <h3 class="item-desc">{{ clothing_item.description|linebreaks }}</h3>
            <div class="sizes">
                <p>Available sizes:
                    <ul class="sizes-list d-flex gap-3">
                        {% for item_size in available_sizes %}
                            <li class="size-name d-flex justify-content-center align-items-center"
                                data-size="{{ item_size.size.name }}">
                                {{ item_size.size.name }}
                            </li>
                        {% empty %}
                            <li>No available sizes.addEventListener</li>
                        {% endfor %}
                    </ul>
                </p>
            </div>
            {% if clothing_item.discount %}
                <div class="cart-discount d-flex gap-2">
                    <p class="line">${{ clothing_item.price }}</p>
                    <p class="price">${{ clothing_item.get_price_with_discount|floatformat:2 }}</p>
                </div>
            {% else %}
                <p class="detail-price">
                    ${{ clothing_item.price }}
                </p>
            {% endif %}
            <div class="detail-cart-form">
                <form action="{% url 'cart:cart_add' clothing_item.id %}" method="post">
                    {% csrf_token %}
                    <div class="select-size d-flex gap-2">
                        <label for="size">Size:</label>
                        <div id="size-display">
                            unselected
                        </div>
                    </div>
                    <input type="hidden" name="size" id="size" required>
                    <button type="submit" class="default-btn mt-3">Add to cart</button>
                </form>
            </div>
        </div>
    </div>

    <script>
        const sizeItems = document.querySelectorAll('.size-name');
        const sizeDisplay = document.getElementById('size-display');
        const sizeInput = document.getElementById('size');

        sizeItems.forEach(item => {
            item.addEventListener('click', () => {
                sizeInput.value = item.getAttribute('data-size');
                sizeDisplay.textContent = item.getAttribute('data-size');
                sizeItems.forEach(i => i.classList.remove('detail-selected'));
                item.classList.add('detail-selected');
            });
        });

        const images = document.querySelectorAll('.detail-image');
        const prevBtn = document.querySelector('.prev-btn');
        const nextBtn = document.querySelector('.next-btn');
        let currentIndex = 0;

        if (images.length > 0) {
            images[currentIndex].style.display = 'block';

            if (images.length === 1) {
                prevBtn.style.display = 'none';
                nextBtn.style.display = 'none';
            } else {
                prevBtn.addEventListener('click', () => {
                    images[currentIndex].style.display = 'none';
                    currentIndex = (currentIndex - 1 + images.length) % images.length;
                    images[currentIndex].style.display = 'block';
                });

                nextBtn.addEventListener('click', () => {
                    images[currentIndex].style.display = 'none';
                    currentIndex = (currentIndex + 1) % images.length;
                    images[currentIndex].style.display = 'block';
                });
            }
        }
    </script>
{% endblock content %}

main/templates/main/product/list.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Reverence Interlude - Catalog{% endblock title %}

{% block content %}
    <h1 class="rev-head text-uppercase" id="app-title">Reverence interlude - ALL</h1>
    <div class="catalog d-flex">
        <form action="{% url "main:catalog" %}" method="get" class="sidebar" id="filter-form">
            <h4 class="price-head">Price Range:</h4>
            <div class="price-range d-flex justify-content-between">
                <input type="number" name="min_price" id="min_price"
                    placeholder="Min Price" value="{{ request.GET.min_price }}" oninput="debounceApplyFilters()">
                <input type="number" name="max_price" id="max_price"
                    placeholder="Max Price" value="{{ request.GET.max_price }}" oninput="debounceApplyFilters()">
            </div>

            <h4 class="category-head">Category:</h4>
            {% for category in categories %}
                <div class="category-option">
                    <input type="checkbox" name="category" id="category-{{ category.slug }}" value="{{ category.slug }}"
                    {% if category.slug in selected_categories %}checked{% endif %} onchange="applyFilters()">
                    <label for="category-{{ category.slug }}" class="d-flex">
                        <div class="category-name">{{ category.name }}</div>
                        <div class="category-len">{{ category.get_item_count }}</div>
                    </label>
                </div>
            {% endfor %}

            <h4 class="size-head">Size:</h4>
            {% for size in sizes %}
                <div class="category-option">
                    <input type="checkbox" name="size" id="size-{{ size.name }}" value="{{ size.name }}"
                    {% if size.name in selected_sizes %}checked{% endif %} onchange="applyFilters()">
                    <label for="size-{{ size.name }}">{{ size.name }}</label>
                </div>
            {% endfor %}
        </form>

        <div class="product-list">
            <div class="card-container d-flex flex-wrap">
                {% for item in clothing_items %}
                    <div class="card">
                        <a href="{% url "main:clothing_item_detail" item.slug %}" class="card-on-catalog">
                            {% if item.image %}
                                <img src="{{ item.image.url }}" alt="{{ item.name }}" class="product-image">
                            {% endif %}
                            <div class="card-info">
                                <h5>{{ item.name }}</h5>
                                {% if item.discount %}
                                    <div class="cart-discount d-flex gap-2">
                                        <p class="line price-on-card">${{ item.price }}</p>
                                        <p class="price">${{ item.get_price_with_discount|floatformat:2 }}</p>
                                    </div>
                                {% else %}
                                    <p class="detail-price">
                                        ${{ item.price }}
                                    </p>
                                {% endif %}
                            </div>
                        </a>
                    </div>
                {% empty %}
                    <p>No products.</p>
                {% endfor %}

            </div>
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const checkboxes = document.querySelectorAll('.category-option input[type="checkbox"]');
            const form = document.getElementById('filter-form')

            checkboxes.forEach(checkbox => {
                checkbox.addEventListener('change', function() {
                    form.submit();
                });
            });
        });

        let timeout;
        function debounceApplyFilters() {
            clearTimeout(timeout);
            timeout = setTimeout(() => {
                const form = document.getElementById('filter-form');
                form.submit();
            }, 1000);
        }

        function applyFilters() {
            const form = document.getElementById('filter-form');
            form.submit();
            updateTitle();
        }

        function updateTitle() {
            const checkboxes = document.querySelectorAll('input[name="category"]:checked');
            const titleElement = document.getElementById('reverence-title');

            if (checkboxes.length > 0) {
                const selectedCategories = Array.from(checkboxes).map(checkbox => {
                    const categoryText = checkbox.nextElementSibling.textContent.trim();
                    return categoryText;
                });
                titleElement.textContent = `REVERENCE INTERLUDE - ${selectedCategories.join(', ')}`;
            } else {
                titleElement.textContent = 'REVERENCE INTERLUDE - ALL';
            }
        }

        document.addEventListener('DOMContentLoaded', updateTitle);
    </script>
{% endblock content %}