app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('main.urls', namespace='main'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from .views import CatalogView, ClothingItemDetailView
from django.urls import path

app_name = 'main'

urlpatterns = [
    path('', CatalogView.as_view(), name='catalog'),
    path('item/<slug:slug>/', ClothingItemDetailView.as_view(),
         name='clothing_item_detail')
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('profile/', views.profile, name='profile'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, \
    BaseUserManager, PermissionsMixin


class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The email field must be set.')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user


    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    middle_name = models.CharField(max_length=30, blank=True)
    city = models.CharField(max_length=30, blank=True)
    street = models.CharField(max_length=30, blank=True)
    house_number = models.CharField(max_length=10, blank=True)
    apartment_number = models.CharField(max_length=10, blank=True)
    postal_code = models.CharField(max_length=10, blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()


    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm, \
    AuthenticationForm
from django.contrib.auth import authenticate
from django import forms
from .models import User


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')
        if password1 and len(password1) < 8:
            self.add_error('password1', 'Minimum 8 characters.')
        return password1


    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        return password2


class UserLoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)


    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if email and password:
            user = authenticate(email=email, password=password)
            if user is None:
                raise forms.ValidationError("Invalid email or password.")
        return self.cleaned_data


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'first_name', 'last_name', 'middle_name',
            'city', 'street', 'house_number',
            'apartment_number', 'postal_code',
        ]

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from .forms import UserRegistrationForm, UserLoginForm, \
    UserProfileForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from orders.models import Order

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('users:user_login')
    else:
        form = UserRegistrationForm()

    return render(request, 'users/register.html', {'form': form})

def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                return redirect('users:profile')
            else:
                form.add_error(None, "Invalid email or password.")
    else:
        form = UserLoginForm()

    return render(request, 'users/login.html', {'form': form})


@login_required(login_url='/users/login')
def user_logout(request):
    logout(request)
    return redirect('users:user_login')

@login_required(login_url='/users/login')
def profile(request):
    user = request.user
    if request.method == 'POST':
        form = UserProfileForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect('users:profile')

    else:
        form = UserProfileForm(instance=user)
    orders = Order.objects.filter(user=user)

    return render(request, 'users/profile.html', {
        'form': form,
        'orders': orders,
    })

users/templates/users/login.html
{% extends "main/base.html" %} {% load static %} {% block title %} Reverence Interlude - Login {% endblock title %} 
{% block content %}
<div class="login-container d-flex justify-content-center">
    <div class="login d-flex flex-column">
        <h3 class="text-center mt-5 mb-5">Login</h3>
        <form method="post" class="loginform">
            {% csrf_token %} {{ form.as_p }}
            <div
                class="loginbtns d-flex justify-content-between align-items-center"
            >
                <button type="submit" class="default-btn mt-2">Login</button>
                <a href="{% url 'users:register' %}" class="create-account-btn"
                    >No account?</a
                >
            </div>
        </form>
    </div>
</div>
{% endblock content %}

users/templates/users/profile.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Reverence Interlude - Profile{% endblock title %}

{% block content %}
    <h1 class="text-center mb-5">Orders history</h1>
    <div class="profile d-flex flex-column gap-4 justify-content-center">
        <div class="profile-history">
            <div class="table-head d-flex justify-content-between align-items-center">
                <div class="left-side-head">
                    <p class="table-p">Product</p>
                </div>
                <div class="right-side-head d-flex gap-3">
                    <p class="table-p c-item-total">Price</p>
                    <p class="table-p c-item-quantity">Quantity</p>
                    <p class="table-p c-item-price">Total</p>
                </div>
            </div>
            <div class="table-items">
                {% if orders|length == 0 %}
                    <div class="empty-orders-message text-center">
                        <h3 class="mt-5">You have no orders.</h3>
                    </div>
                {% else %}
                    {% for order in orders %}
                        <div class="order">
                            Order №{{ order.id }}
                            {% for item in order.items.all %}
                                <div class="order-item d-flex justify-content-between align-items-center">
                                    <div class="left-side-items d-flex">
                                        <div class="c-item-img">
                                            <img src="{{ item.clothing_item.image.url }}" alt="">
                                        </div>
                                        <div class="c-item-info">
                                            <a href="{% url "main:clothing_item_detail" item.clothing_item.slug %}"
                                                class="item-name-in-cart p-3">{{ item.item.name }}</a>
                                            <p class="item-size-bottom fw-bold p-3">{{ item.size }}</p>
                                        </div>
                                    </div>
                                    <div class="right-side-items d-flex gap-3">
                                        <div class="c-item-price">
                                            ${{ item.total_price|floatformat:2 }}
                                        </div>
                                        <div class="c-item-quantity">
                                            1
                                        </div>
                                        <div class="c-item-total">
                                            ${{ item.total_price|floatformat:2 }}
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="track mt-2">Tracking number: {{ order.tracking_number }}</div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>

    <div class="profile-info">
        <h3 class="mb-5 mt-5">Ordering data</h3>
        <form method="post" class="profile-form">
            {% csrf_token %}
            <div class="form-blocks d-flex gap-4">
                <div class="block1 d-flex flex-column gap-1">
                    {{ form.first_name.label_tag }} {{ form.first_name }} <br>
                    {{ form.last_name.label_tag }} {{ form.last_name }} <br>
                    {{ form.middle_name.label_tag }} {{ form.middle_name }} <br>
                    {{ form.city.label_tag }} {{ form.city }} <br>
                    {{ form.street.label_tag }} {{ form.street }} <br>
                    {{ form.house_number.label_tag }} {{ form.house_number }} <br>
                </div>
                <div class="block2 d-flex flex-column gap-1">
                    {{ form.apartment_number.label_tag }} {{ form.apartment_number }} <br>
                    {{ form.postal_code.label_tag }} {{ form.postal_code }} <br>
                    <div class="p-on-order d-flex flex-column justify-content-center align-items-center">
                        <p class="block-tag mt-4 text-center">The information will be used when placing an order.</p>
                    </div>
                </div>
            </div>
            <div class="profile-buttons mt-4 d-flex justify-content-between">
                <button class="default-btn profile-btn">Save</button>
                <a href="{% url 'users:user_logout' %}" class="logout-btn d-flex align-items-center">Log out of your account</a>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/register.html
{% extends "main/base.html" %} {% load static %} {% block title %} Reverence Interlude - Registration {% endblock title %} 
{% block content %}
<div class="login-container d-flex justify-content-center">
    <div class="login d-flex flex-column">
        <h3 class="text-center mt-5 mb-5">Registration</h3>
        <form method="post" class="loginform">
            {% csrf_token %} {% for field in form %}
            <div class="form-group mb-3 d-flex flex-column">
                {{ field.label_tag }} {{ field }} {% if field.errors %}
                <div class="error">{{ field.errors }}</div>
                {% endif %}
            </div>
            {% endfor %}
            <div
                class="loginbtns d-flex justify-content-between align-items-center"
            >
                <button type="submit" class="default-btn mt-3">Register</button>
                <a
                    href="{% url 'users:user_login' %}"
                    class="create-account-btn"
                    >Have account?</a
                >
            </div>
        </form>
    </div>
</div>
{% endblock content %}