app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('main.urls', namespace='main'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:item_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:item_id>/', views.cart_remove, name='cart_remove'),
    path('update/<int:item_id>/', views.CartUpdateView.as_view(), name='cart_update'),
]

main/urls.py
from .views import CatalogView, ClothingItemDetailView
from django.urls import path

app_name = 'main'

urlpatterns = [
    path('', CatalogView.as_view(), name='catalog'),
    path('item/<slug:slug>/', ClothingItemDetailView.as_view(),
         name='clothing_item_detail')
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('profile/', views.profile, name='profile'),
]

main/models.py
from django.db import models


class Size(models.Model):
    name = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name'])]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_item_count(self):
        return ClothingItem.objects.filter(category=self).count()

class ClothingItem(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    available = models.BooleanField(default=True)
    sizes = models.ManyToManyField(Size, through='ClothingItemSize',
                                   related_name='clothing_item', blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE,
                                 related_name='clothing_items')
    image = models.ImageField(upload_to='product/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True)
    price = models.DecimalField(max_digits=20, decimal_places=2)
    discount = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return self.name

    def get_price_with_discount(self):
        if self.discount > 0:
            return round(self.price * (1 - (self.discount / 100)), 2)
        return round(self.price, 2)

class ClothingItemSize(models.Model):
    clothing_item = models.ForeignKey(ClothingItem, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    available = models.BooleanField(default=True)

    class Meta:
        unique_together = ('clothing_item', 'size')

class ItemImage(models.Model):
    product = models.ForeignKey(ClothingItem, related_name='images',
                                on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product/%Y/%m/%d', blank=True)

    def __str__(self):
        return f'{self.product.name} - {self.image.name}'

main/views.py
from django.views.generic import ListView, DetailView
from .models import ClothingItem, Category, Size, \
    ClothingItemSize
from django.db.models import Q


class CatalogView(ListView):
    model = ClothingItem
    template_name = 'main/product/list.html'
    context_object_name = 'clothing_items'


    def get_queryset(self):
        queryset = super().get_queryset()
        category_slugs = self.request.GET.getlist('category')
        size_names = self.request.GET.getlist('size')
        min_price = self.request.GET.get('min_price')
        max_price = self.request.GET.get('max_price')
        search_query = self.request.GET.get('q')

        if category_slugs:
            queryset = queryset.filter(category__slug__in=category_slugs)

        if size_names:
            queryset = queryset.filter(
                Q(sizes__name__in=size_names) & Q(sizes__clothingitemsize__available=True)
            ).distinct()

        if min_price:
            queryset = queryset.filter(price__gte=min_price)

        if max_price:
            queryset = queryset.filter(price__lte=max_price)

        if search_query:
            queryset = queryset.filter(
                Q(name__icontains=search_query) |
                Q(description__icontains=search_query)
            ).distinct()

        return queryset


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['sizes'] = Size.objects.all()
        context['selected_categories'] = self.request.GET.getlist('category')
        context['selected_sizes'] = self.request.GET.getlist('size')
        context['min_price'] = self.request.GET.get('min_price', '')
        context['max_price'] = self.request.GET.get('max_price', '')

        return context


class ClothingItemDetailView(DetailView):
    model = ClothingItem
    template_name = 'main/product/detail.html'
    context_object_name = 'clothing_item'
    slug_field = 'slug'
    slug_url_kwarg = 'slug'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        clothing_item = self.object
        available_sizes = ClothingItemSize.objects.filter(clothing_item=clothing_item,
                                                           available=True)
        context['available_sizes'] = available_sizes
        return context

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>

    {% comment %} bootstrap {% endcomment %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">

    {% comment %} css {% endcomment %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    <header class="header sticky-top d-flex align-items-center">
        <a class="header-logo" href="{% url "main:catalog" %}">
            <img src="{% static 'img/rev.png' %}" alt="">
        </a>
        {% comment %} <div class="search">
            <form action="" id="search-form" class="search_form d-flex" style="display: none;">
                <input type="text" name="q" class="form_input" placeholder="Search">
                <button type="submit" class="btnforsearch"></button>
            </form>
        </div> {% endcomment %}
        <div class="header-nav d-flex gap-4">
            <a href="{% url 'users:profile' %}" class="h-profile">
                <img src="{% static 'img/profile.png' %}" alt="">
            </a>
            <a href="{% url 'cart:cart_detail' %}" class="h-profile">
                <img src="{% static 'img/cart.png' %}" alt="">
            </a>
            <div class="forsearch">
                <a href="#" id="toggle-search" class="toggle-search">
                    <img src="{% static 'img/search.png' %}" alt="">
                </a>
                <div class="search-popup" id="search-popup" style="display: none;">
                    <form class="search-form" method="GET" action="{% url 'main:catalog' %}" id="search-form">
                        <div class="input-container">
                            <input type="text" class="form_input" name="q" placeholder="Search" value="{{ search_query }}">
                            <button type="submit" class="btnforsearch"></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </header>

    <div class="container">
        {% block content %}{% endblock content %}
    </div>

    <script>
        document.getElementById('toggle-search').addEventListener('click', function(event) {
            event.preventDefault();
            const searchPopup = document.getElementById('search-popup');

            if (searchPopup.style.display === 'none' || searchPopup.style.display === '') {
                searchPopup.style.display = 'block';
            } else {
                searchPopup.style.display = 'none';
            }
        })
    </script>

    {% comment %} js for bootstrap {% endcomment %}
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>